# Generated by Django 2.2.3 on 2019-08-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0002_auto_20190828_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticketprice',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='Employ_id',
            field=models.PositiveIntegerField(default='4459'),
        ),
    ]
