# Generated by Django 2.2.3 on 2019-08-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0003_auto_20190828_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticketprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Employ_id',
            field=models.PositiveIntegerField(default='7002'),
        ),
    ]
