# Generated by Django 2.2.3 on 2019-08-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0006_auto_20190830_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Employ_id',
            field=models.PositiveIntegerField(default='5555'),
        ),
    ]
