# Generated by Django 2.2.3 on 2019-09-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0007_auto_20190830_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Vistorname',
            new_name='Visitorname',
        ),
        migrations.AlterField(
            model_name='registration',
            name='Employ_id',
            field=models.PositiveIntegerField(default='8432'),
        ),
    ]
