# Generated by Django 2.2.3 on 2019-09-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0008_auto_20190903_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Visitorname',
            new_name='Vistorname',
        ),
        migrations.AlterField(
            model_name='registration',
            name='Employ_id',
            field=models.PositiveIntegerField(default='2366'),
        ),
    ]
