# Generated by Django 2.2.3 on 2019-09-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0009_auto_20190903_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Employ_id',
            field=models.PositiveIntegerField(default='3551'),
        ),
    ]
